"""Planner agent responsible for decomposing user requests into validated DAG execution plans."""

import time
from typing import Any, Dict, List, Optional, Set

from pydantic import BaseModel, Field

from enterprise_orchestrator.agents.base import AgentMetadata, BaseAgent
from enterprise_orchestrator.agents.result import AgentResult, AgentStatus
from enterprise_orchestrator.core.state import OrchestrationState
from enterprise_orchestrator.core.task import ExecutionPlan, Task
from enterprise_orchestrator.core.types import AgentRole, MessageRole, TaskStatus, TaskType
from enterprise_orchestrator.errors.exceptions import OrchestratorError, ValidationError
from enterprise_orchestrator.providers.models import LLMRequest, Message
from enterprise_orchestrator.providers.router import LLMRouter


class PlannedTaskItem(BaseModel):
    """Schema model for an individual task item produced by the LLM planner."""

    id: str = Field(..., min_length=1, description="Unique task identifier (e.g. task_1, fetch_data)")
    title: str = Field(..., min_length=1, description="Concise task title")
    description: str = Field(default="", description="Detailed execution instructions")
    task_type: TaskType = Field(default=TaskType.CUSTOM, description="Task category: retrieval, tool_execution, synthesis, custom")
    assigned_agent: AgentRole = Field(default=AgentRole.CUSTOM, description="Assigned agent role")
    dependencies: List[str] = Field(default_factory=list, description="IDs of tasks that must finish before this task starts")
    input_data: Dict[str, Any] = Field(default_factory=dict, description="Structured task input payload")


class PlannedDecompositionSchema(BaseModel):
    """Schema model for the complete structured plan generated by the LLM."""

    rationale: str = Field(..., min_length=1, description="High-level architectural rationale and strategy")
    tasks: List[PlannedTaskItem] = Field(..., min_length=1, description="List of discrete tasks forming a valid DAG")


class PlannerAgent(BaseAgent):
    """Agent that analyzes requirements and constructs a validated Directed Acyclic Graph (DAG) ExecutionPlan."""

    def __init__(self, router: LLMRouter) -> None:
        metadata = AgentMetadata(
            name="planner_agent",
            role=AgentRole.PLANNER,
            description="Decomposes user objectives into dependency-linked execution task graphs",
            capabilities=["task_decomposition", "dag_generation", "dependency_analysis"],
            input_schema_desc="OrchestrationState with valid request string",
            output_schema_desc="ExecutionPlan containing validated DAG tasks",
        )
        super().__init__(metadata=metadata)
        self.router = router

    def validate_input(self, state: OrchestrationState, task: Optional[Task] = None) -> bool:
        """Verify the state contains an actionable user request."""
        return bool(state.request and state.request.strip())

    def validate_plan_dag(self, plan_data: PlannedDecompositionSchema) -> None:
        """Validate topological integrity: no duplicates, no missing dependencies, no cycles."""
        if not plan_data.tasks:
            raise ValidationError(
                message="Planner generated an empty task list.",
                code="EMPTY_PLAN",
                retryable=True,
            )

        task_ids: List[str] = [t.id for t in plan_data.tasks]

        # 1. Check for duplicate task IDs
        if len(task_ids) != len(set(task_ids)):
            seen = set()
            duplicates = [x for x in task_ids if x in seen or seen.add(x)]
            raise ValidationError(
                message=f"Plan contains duplicate task IDs: {duplicates}",
                code="DUPLICATE_TASK_IDS",
                retryable=True,
            )

        task_id_set = set(task_ids)

        # 2. Check for self-dependencies or missing dependency references
        for t in plan_data.tasks:
            if t.id in t.dependencies:
                raise ValidationError(
                    message=f"Task '{t.id}' cannot depend on itself (self-dependency detected).",
                    code="SELF_DEPENDENCY",
                    retryable=True,
                )
            for dep in t.dependencies:
                if dep not in task_id_set:
                    raise ValidationError(
                        message=f"Task '{t.id}' references non-existent dependency '{dep}'.",
                        code="INVALID_DEPENDENCY_REFERENCE",
                        retryable=True,
                    )

        # 3. Check for cycles using Kahn's Algorithm (Topological Sort)
        in_degree = {t_id: 0 for t_id in task_ids}
        dependents: Dict[str, List[str]] = {t_id: [] for t_id in task_ids}

        for t in plan_data.tasks:
            for dep in t.dependencies:
                dependents[dep].append(t.id)
                in_degree[t.id] += 1

        queue = [t_id for t_id, deg in in_degree.items() if deg == 0]
        visited_count = 0

        while queue:
            node = queue.pop(0)
            visited_count += 1
            for nxt in dependents[node]:
                in_degree[nxt] -= 1
                if in_degree[nxt] == 0:
                    queue.append(nxt)

        if visited_count != len(task_ids):
            raise ValidationError(
                message="Plan contains cyclic dependencies (not a valid DAG).",
                code="CYCLIC_PLAN_DEPENDENCY",
                retryable=True,
            )

    async def execute(self, state: OrchestrationState, task: Optional[Task] = None) -> AgentResult:
        """Decompose request into a validated ExecutionPlan using LLMRouter."""
        start_time = time.perf_counter()

        if not self.validate_input(state, task):
            return AgentResult.failure(
                agent_name=self.name,
                error="State request is empty or invalid for planning.",
                retryable=False,
                execution_time_ms=(time.perf_counter() - start_time) * 1000,
            )

        system_prompt = (
            "You are an expert Lead Technical Architect & Workflow Planner for an Enterprise Multi-Agent Orchestration Framework.\n"
            "Your objective is to analyze the user request and decompose it into discrete, dependency-linked tasks.\n"
            "Guidelines:\n"
            "1. Each task must have a unique ID (e.g. 'task_1', 'search_docs', 'calc_tax').\n"
            "2. Establish dependencies where tasks depend on output from earlier tasks.\n"
            "3. Assign appropriate task_type (retrieval, tool_execution, synthesis, custom) and assigned_agent.\n"
            "4. Ensure tasks form a strict Directed Acyclic Graph (DAG) with no cycles."
        )

        user_prompt = f"User Request:\n{state.request}\n"
        if state.custom_context:
            user_prompt += f"\nAdditional Context:\n{state.custom_context}"

        req = LLMRequest(
            messages=[
                Message(role=MessageRole.SYSTEM, content=system_prompt),
                Message(role=MessageRole.USER, content=user_prompt),
            ],
            temperature=0.2,
        )

        try:
            parsed_plan, llm_resp = await self.router.generate_structured(req, PlannedDecompositionSchema)

            # Enforce DAG validation
            self.validate_plan_dag(parsed_plan)

            # Convert to domain ExecutionPlan & Task objects
            domain_tasks = [
                Task(
                    id=t.id,
                    title=t.title,
                    description=t.description,
                    task_type=t.task_type,
                    assigned_agent=t.assigned_agent,
                    dependencies=t.dependencies,
                    status=TaskStatus.PENDING,
                    input_data=t.input_data,
                )
                for t in parsed_plan.tasks
            ]

            execution_plan = ExecutionPlan(
                tasks=domain_tasks,
                rationale=parsed_plan.rationale,
            )

            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.success(
                agent_name=self.name,
                output={"execution_plan": execution_plan.model_dump()},
                raw_response=llm_resp.content,
                execution_time_ms=latency_ms,
                metadata={"provider": llm_resp.provider, "model": llm_resp.model, "total_tasks": len(domain_tasks)},
            )

        except ValidationError as e:
            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.failure(
                agent_name=self.name,
                error=f"Plan validation failed: {e.message}",
                retryable=e.retryable,
                execution_time_ms=latency_ms,
                metadata={"code": e.code},
            )
        except OrchestratorError as e:
            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.failure(
                agent_name=self.name,
                error=f"Provider error during planning: {e.message}",
                retryable=e.retryable,
                execution_time_ms=latency_ms,
                metadata={"code": e.code},
            )
        except Exception as e:
            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.failure(
                agent_name=self.name,
                error=f"Unexpected error in PlannerAgent: {e}",
                retryable=False,
                execution_time_ms=latency_ms,
            )
