"""Validator and critic agent responsible for automated output quality and criteria verification."""

import time
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from enterprise_orchestrator.agents.base import AgentMetadata, BaseAgent
from enterprise_orchestrator.agents.result import AgentResult, AgentStatus
from enterprise_orchestrator.core.state import OrchestrationState
from enterprise_orchestrator.core.task import Task
from enterprise_orchestrator.core.types import AgentRole, MessageRole, ValidationStatus
from enterprise_orchestrator.errors.exceptions import OrchestratorError, ValidationError
from enterprise_orchestrator.providers.models import LLMRequest, Message
from enterprise_orchestrator.providers.router import LLMRouter
from enterprise_orchestrator.validation.models import ValidationResult


class CriticEvaluationSchema(BaseModel):
    """Schema model for structured critique generated by the LLM."""

    is_valid: bool = Field(..., description="True if output completely satisfies acceptance criteria and task objective")
    status: ValidationStatus = Field(..., description="VALID, NEEDS_RETRY, or NEEDS_HUMAN_REVIEW")
    score: float = Field(..., ge=0.0, le=1.0, description="Quality or confidence score from 0.0 to 1.0")
    feedback: str = Field(..., min_length=1, description="Concise, actionable feedback explaining the decision")
    issues: List[str] = Field(default_factory=list, description="List of specific flaws, inaccuracies, or missing items")
    needs_retry: bool = Field(default=False, description="True if a bounded retry could resolve the issue")
    needs_human_review: bool = Field(default=False, description="True if ambiguity, high-risk, or severe uncertainty requires human intervention")


class ValidatorAgent(BaseAgent):
    """Quality-gate critic agent that evaluates candidate task outputs against specifications."""

    def __init__(self, router: LLMRouter) -> None:
        metadata = AgentMetadata(
            name="validator_agent",
            role=AgentRole.VALIDATOR,
            description="Evaluates agent outputs against acceptance criteria to ensure accuracy, safety, and completeness",
            capabilities=["quality_gate", "semantic_validation", "critique_generation"],
            input_schema_desc="Task input with 'target_output' and 'acceptance_criteria', or state output",
            output_schema_desc="ValidationResult with validity status, feedback, and score",
        )
        super().__init__(metadata=metadata)
        self.router = router

    def validate_input(self, state: OrchestrationState, task: Optional[Task] = None) -> bool:
        """Check if candidate output is provided in task or state."""
        if task and task.input_data and "target_output" in task.input_data:
            return True
        # Or check if any agent outputs or final response exist in state
        return bool(state.agent_outputs or state.final_response or (task and task.output_data))

    async def execute(self, state: OrchestrationState, task: Optional[Task] = None) -> AgentResult:
        """Evaluate candidate output using LLMRouter and produce structured ValidationResult."""
        start_time = time.perf_counter()

        if not self.validate_input(state, task):
            return AgentResult.failure(
                agent_name=self.name,
                error="No target output found to validate.",
                retryable=False,
                execution_time_ms=(time.perf_counter() - start_time) * 1000,
            )

        # Extract target output and criteria
        target_output = None
        criteria = "Must be accurate, factual, well-structured, and directly address the user objective."
        task_id = None

        if task and task.input_data:
            target_output = task.input_data.get("target_output")
            if "acceptance_criteria" in task.input_data:
                criteria = str(task.input_data["acceptance_criteria"])
            task_id = task.id

        if target_output is None:
            if task and task.output_data:
                target_output = task.output_data
            elif state.agent_outputs:
                target_output = state.agent_outputs
            else:
                target_output = state.final_response

        system_prompt = (
            "You are an impartial Quality Gate & Critic Evaluator for an Enterprise Multi-Agent System.\n"
            "Your sole objective is to evaluate whether the Candidate Output satisfies the Task Objective and Acceptance Criteria.\n"
            "Rules:\n"
            "1. Do NOT generate or rewrite the answer yourself. Strictly evaluate.\n"
            "2. Determine status: VALID (fully acceptable), NEEDS_RETRY (fixable via prompt/re-run), or NEEDS_HUMAN_REVIEW (high-risk, ambiguous, or irreversible).\n"
            "3. Provide constructive feedback and list specific issues if invalid.\n"
            "4. Score between 0.0 and 1.0."
        )

        user_prompt = (
            f"Original Request:\n{state.request}\n\n"
            f"Acceptance Criteria:\n{criteria}\n\n"
            f"Candidate Output to Evaluate:\n{target_output}\n"
        )

        req = LLMRequest(
            messages=[
                Message(role=MessageRole.SYSTEM, content=system_prompt),
                Message(role=MessageRole.USER, content=user_prompt),
            ],
            temperature=0.1,
        )

        try:
            critique, llm_resp = await self.router.generate_structured(req, CriticEvaluationSchema)

            validation_result = ValidationResult(
                is_valid=critique.is_valid,
                status=critique.status,
                score=critique.score,
                feedback=critique.feedback,
                issues=critique.issues,
                needs_retry=critique.needs_retry,
                needs_human_review=critique.needs_human_review,
                validator_name=self.name,
                evaluated_task_id=task_id,
                metadata={"provider": llm_resp.provider, "model": llm_resp.model},
            )

            # Record in state
            state.add_validation_result(validation_result)
            latency_ms = (time.perf_counter() - start_time) * 1000

            if validation_result.needs_human_review:
                return AgentResult.escalate(
                    agent_name=self.name,
                    reason=f"Validation escalated to human review: {validation_result.feedback}",
                    context={"validation": validation_result.model_dump()},
                    execution_time_ms=latency_ms,
                )

            return AgentResult.success(
                agent_name=self.name,
                output={"validation": validation_result.model_dump()},
                raw_response=llm_resp.content,
                execution_time_ms=latency_ms,
                metadata={"is_valid": validation_result.is_valid, "status": validation_result.status.value},
            )

        except OrchestratorError as e:
            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.failure(
                agent_name=self.name,
                error=f"Critic evaluation provider error: {e.message}",
                retryable=e.retryable,
                execution_time_ms=latency_ms,
                metadata={"code": e.code},
            )
        except Exception as e:
            latency_ms = (time.perf_counter() - start_time) * 1000
            return AgentResult.failure(
                agent_name=self.name,
                error=f"Unexpected error in ValidatorAgent: {e}",
                retryable=False,
                execution_time_ms=latency_ms,
            )
