"""Human-in-the-loop escalation and decision contracts."""

from datetime import datetime
from typing import Any, Dict, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from enterprise_orchestrator.core.metadata import utc_now
from enterprise_orchestrator.core.types import HumanRequestStatus


class HumanEscalationRequest(BaseModel):
    """Request generated by an agent or supervisor requiring human approval or intervention."""

    request_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique ID for this escalation request")
    run_id: str = Field(..., description="ID of the associated orchestration run")
    task_id: Optional[str] = Field(default=None, description="Associated task ID if escalation arose from a specific task")
    reason: str = Field(..., min_length=1, description="Explicit reason why human intervention is required")
    requested_action: str = Field(..., description="Description of the action or decision required from the human")
    context: Dict[str, Any] = Field(default_factory=dict, description="Contextual payload and state snapshots provided for review")
    status: HumanRequestStatus = Field(default=HumanRequestStatus.PENDING, description="Current status of the escalation")
    created_at: datetime = Field(default_factory=utc_now, description="Timestamp when escalation was requested")
    resolved_at: Optional[datetime] = Field(default=None, description="Timestamp when decision was submitted")


class HumanDecision(BaseModel):
    """Human reviewer response resolving an escalation request."""

    request_id: str = Field(..., description="ID of the escalation request being resolved")
    status: HumanRequestStatus = Field(..., description="Verdict: APPROVED, REJECTED, or MODIFIED")
    decision_note: Optional[str] = Field(default=None, description="Optional commentary or reasoning from the reviewer")
    modified_payload: Optional[Dict[str, Any]] = Field(default=None, description="Alternative or updated parameters if MODIFIED")
    reviewer_id: Optional[str] = Field(default=None, description="Identifier of the human reviewer")
    resolved_at: datetime = Field(default_factory=utc_now, description="Timestamp when decision was recorded")
